rootProject.name = 'fabric-tooling'

include "class-tweaker"
include "fabric-log4j-util"
include "dev-launch-injector"
include "intermediary-forwarder"
include "rename-tool"

def buildNative = file(".nativeEnabled").exists() || System.getenv('CI') != null
def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')

if (buildNative) {
	include 'native:third-party:google-test'

	if (isWindows) {
		include "fabric-loom-native"

		include 'native:windows:fabric-loom-native'
	}
}
